### ISSUE TITLE
Doesn't work with A9lh and latest Launcher.dat

### ISSUE THREAD

**Issue by urherenow** [Rohul1997/Gateway_cia#1]
Gateway 3.7.1

A9lh booting AuReinand into 9.2 sysnand using the 9.0 firm (official GW.3dsx works fine through HBL/CTRBootManager).
This hangs on either a white bottom screen or a red bottom screen using installed .cia file.

Edit: I am, however, using @Steveice10 's fork of ctrulib. Which version are you using so I can give that a try?

**Comment by Rohul1997** [comment]
Are you compiling and then trying it? If so then could you try the one on the release and see if it works and then report back.
I'm using the latest version of ctrulib, you have to use the latest or else it won't compile.

**Comment by urherenow** [comment]
Compiled myself and got no warnings. I don't even see a release tab in this git. Did you make one, and did you make it private or something?

**Comment by Rohul1997** [comment]
Its not private at all it is there.
https://github.com/Rohul1997/Gateway_cia/releases

**Comment by Rohul1997** [comment]
oh I think I know what your problem might be, theres a file called gate.3dsx that is included put that on the root of your sd card

**Comment by urherenow** [comment]
Hmmm... You're probably right. I'll have to check when I get back home. Mind if I adjust the readme.MD and make a pull request later on though?

**Comment by Rohul1997** [comment]
You may. Is there anything I got to do I'm kind of new to github?

**Comment by urherenow** [comment]
#2 Makes things clearer, I think. I also think that the appeal of this is to be able to launch GW without using another loader first, since there is already an official GW.3dsx. So... what is the point of Gateway_cia.3dsx? Is that also an installer? If so, I guess my readme PR needs more tweaking...

By the way, placing the gate.3dsx in root fixed me up, but on the second try. The first try, I hung on a white bottom screen on my 9.2 o3ds (a9lh).

**Comment by urherenow** [comment]
Anyway, this issue can be closed. I am wondering if this can be adapted to an arm9loaderhax.bin though, for even faster booting into Gateway. If Key init is a problem then it should be able to work like Decrypt9 does with the several key.bin files it needs with an a9lh boot...
